# Generated by Django 4.2.4 on 2023-12-01 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('dbf05025-5dbf-42ea-aec9-92989109bf8f'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('JOB_POSTING', 'JOB_POSTING')])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('amount', models.CharField()),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING')),
                ('product_reference_id', models.UUIDField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d2233851-fe91-4717-81c9-a8a05667c720'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.order')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('75dbdbf7-762d-4066-aba4-9f009b79978d'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('amount', models.TextField()),
                ('notes', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
