# Generated by Django 4.2.4 on 2023-12-01 19:41

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.CharField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('is_application_native', models.BooleanField(default=False)),
                ('is_salary_included', models.BooleanField(default=False)),
                ('salary', models.IntegerField(blank=True)),
                ('salary_period', models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], default='MONTHLY')),
                ('salary_currency', models.CharField(blank=True, max_length=3)),
                ('description', ckeditor.fields.RichTextField()),
                ('mode_of_work', models.CharField(choices=[('IN-OFFICE', 'IN-OFFICE'), ('HYBRID', 'HYBRID'), ('REMOTE', 'REMOTE')])),
                ('work_location', models.CharField(max_length=200)),
                ('minimum_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('application_url', models.URLField(blank=True)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('post_status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED')], default='DRAFT')),
                ('online_until', models.DateTimeField(blank=True, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('employer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.employer')),
            ],
            managers=[
                ('jobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_link', models.URLField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('employer_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPLIED', 'APPLIED'), ('IN-REVIEW', 'IN-REVIEW'), ('REJECTED', 'REJECTED'), ('OFFERED', 'OFFERED')])),
                ('education_level', models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('TERTIARY', 'TERTIARY'), ('GRADUATE', 'GRADUATE'), ('POST-GRADUATE', 'POST-GRADUATE')])),
                ('years_of_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='jobs_job_search_e0df70_gin'),
        ),
    ]
