# Generated by Django 4.2.4 on 2023-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Bangladeshi Company', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Dhaka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='minimum_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
