# Generated by Django 4.2.4 on 2023-09-01 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_application_email_alter_job_application_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_characters', message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9 _.,-+=`~\\|><@#$%^&*()!"\'/$]*$')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(default='now', verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_characters', message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9 _.,-+=`~\\|><@#$%^&*()!"\'/$]*$')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_characters', message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9 _.,-+=`~\\|><@#$%^&*()!"\'/$]*$')]),
        ),
    ]
