# Generated by Django 4.2.4 on 2023-09-06 13:43

import django.contrib.postgres.indexes
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import migrations

def compute_search_vector(apps, schema_editor):
    Jobs = apps.get_model("jobs", "Job")
    Jobs.objects.update(search=(
            SearchVector('title', weight='A') 
            + SearchVector('description', weight='B')
            + SearchVector('location', weight='C')
            + SearchVector('company_name', weight='D')
        ))

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search',
            field=SearchVectorField(null=True),
        ),
        migrations.RunPython(compute_search_vector, reverse_code=lambda a, b: None)
        ,
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='jobs_job_search_e0df70_gin'),
        ),
    ]
